### ISSUE TITLE
18.0 onwards builds unavailable on GitHub

### ISSUE THREAD

**Issue by TheComputerNerd88** [JonasJurczok/factorio-todo-list#153]
Version 18.0.0 and 18.0.1 releases are unavailable on GitHub - only available on [the mods portal](mods.factorio.com). 

By the way, what is the compile process for this mod? The releases' file structure differs from the source code structure here.

**Comment by JonasJurczok** [comment]
Hi,
yeah.

The compilation uses [Faketorio](https://github.com/jonasjurczok/faketorio). But github actions got released and all my actions are unusable now because the syntax changed drastically.

So far I haven't got the time to fix everything.
Hence the releases only being available on the mod portal and not here anymore...

**Comment by JonasJurczok** [comment]
All new releases are available again :)
