### ISSUE TITLE
Error Code

### ISSUE THREAD

**Issue by Sehtek** [JonasJurczok/factorio-todo-list#212]
Error while running event Todo-List-Continued::on_gui_click (ID 1)
__Todo-List-Continued__/todo/features/export_task.lua:6: attempt to index global 'global' (a nil value)
stack traceback:
	__Todo-List-Continued__/todo/features/export_task.lua:6: in function 'update_export_dialog_button_state'
	__Todo-List-Continued__/todo/ui/main_frame.lua:57: in function 'create_maximized_frame'
	__Todo-List-Continued__/todo/features/main_ui.lua:69: in function 'maximize_main_frame'
	__Todo-List-Continued__/todo/features/main_ui.lua:58: in function 'on_maximize_button_click'
	__Todo-List-Continued__/todo/todo.lua:94: in function 'on_gui_click'
	__Todo-List-Continued__/control.lua:20: in function <__Todo-List-Continued__/control.lua:19>

Appeared when i just clicked the butten on the top left corner in game

**Comment by emteeoh** [comment]
I'm running a headless server and get basically the same error. It happens any time I try to look at the todo list, or when I try to finish adding a new task to the list.  Here's my server's output:

14016.944 Error ServerMultiplayerManager.cpp:84: MultiplayerManager failed: "The mod ✔ Todo List - Continued (20.0.2) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event Todo-List-Continued::on_gui_click (ID 1)
__Todo-List-Continued__/todo/features/export_task.lua:6: attempt to index global 'global' (a nil value)
stack traceback:
	__Todo-List-Continued__/todo/features/export_task.lua:6: in function 'update_export_dialog_button_state'
	__Todo-List-Continued__/todo/ui/main_frame.lua:57: in function 'create_maximized_frame'
	__Todo-List-Continued__/todo/features/main_ui.lua:69: in function 'maximize_main_frame'
	__Todo-List-Continued__/todo/features/main_ui.lua:58: in function 'on_maximize_button_click'
	__Todo-List-Continued__/todo/todo.lua:94: in function 'on_gui_click'
	__Todo-List-Continued__/control.lua:20: in function <__Todo-List-Continued__/control.lua:19>"

**Comment by Alexander-Serov** [comment]
Hello there!

Thank you for reaching out and reporting this issue. It looks like you're using the "✔ Todo List - Continued" mod, which isn’t the version maintained in this repository. From what I understand, the other repository might have been removed by its author, which could be why you ended up here. Unfortunately, that means you can’t report the issue to them anymore.

The good news is that the issue you mentioned has already been resolved in the version of the mod maintained here! 🎉 To fix your problem, you can install this version by searching for "✔ Todo List" in the Factorio mods list.

I’ll go ahead and close this issue since the current mod doesn’t have the described problem. But please don’t hesitate to open a new issue if you run into any other bugs or need further help.

Happy optimizing and happy building! 🚀
