### ISSUE TITLE
0.16.22 compatibility issue

### ISSUE THREAD

**Issue by sapid** [JonasJurczok/factorio-todo-list#22]
When clicking the `Todo List` button at top left:
```Error while running event Todo-List::on_gui_click (ID 1)
Key "column_count" not found in property tree at ROOT
stack traceback:
	__Todo-List__/UI.lua:52: in function 'create_task_table'
	__Todo-List__/UI.lua:22: in function 'create_maximized_frame'
	__Todo-List__/todo.lua:45: in function 'maximize'
	__Todo-List__/todo.lua:187: in function 'on_gui_click'
	__Todo-List__/control.lua:18: in function <__Todo-List__/control.lua:17>```

**Comment by JonasJurczok** [comment]
Hi,
thanks for the report. It is already fixed in the bugfix branch and I'm planning on releasing the new version hopefully this weekend, maybe earlier.

If you don't want to wait this long you can open the UI.lua in your local installation, navigate to line 52 and replace the "colspan" with "column_count". Everything should work as expected afterwards.

**Comment by JonasJurczok** [comment]
A new version has been released. Thanks again for the bugreport. If anything pops up in the future I would be thankful for another issue here :)

Have fun and happy building.

**Comment by sapid** [comment]
Hooray! Thanks so much for the prompt fix! I'm really excited to add this to my server's modpack.
