### ISSUE TITLE
Details field on tasks

### ISSUE THREAD

**Issue by hoylemd** [JonasJurczok/factorio-todo-list#45]
Right now, tasks support multi-line, and this might be helpful for particularly complicated things.  Unfortunately, they take of a lot of space in the UI.

If we had separate 'title' and an optional 'details' field, we could force the title to be one line (maybe even a length limit), and allow users to elaborate all they want in the multi-line details field.

This would make the UI a lot easier to develop, since every task in the list will take up the same amount of space.

**Comment by hoylemd** [comment]
Huh, I'm trying to add the 'enhancement' label, but github won't let me :c

**Comment by hoylemd** [comment]
Actually, this is a duplicate of #35

**Comment by Tarrke** [comment]
Not really. Both ideas are complementary In my opinion.

**Comment by hoylemd** [comment]
Oh, well in that case...

**Comment by JonasJurczok** [comment]
We had a similar idea in the beginning. Ideally you only see the title and
then have basically a collapsible cell with the details below, thus
enabling you to expand and minimize individual tasks. We dropped the idea
because rerendering the table is quite expensive and you have to track a
lot of state.

On the other hand: my understanding of liability grew a lot and by now it
might actually be worth a try. I would combine this with #35 though. It is
essentially the same idea, just a question of representation.

What do you guys think?

**Comment by Tarrke** [comment]
Maybe my inderstanding of #35 is not the good one... Here I read a task divided in title and detailed descriptions. In #35 I read adding a button to get a complex view of a task, providing information on it (like the title, a complex description, and more).

Both ideas are great to me.

**Comment by hoylemd** [comment]
I think this and #35 are closely related, but ultimately describe different things.  Or to put it another way, The solution to one will probably solve the other with minor modifications.

We could probably merge the issues.

**Comment by JonasJurczok** [comment]
My reasoning would be that it is unlikely to release a version with one but
not the other. Ultimately it is not important though D

>

**Comment by JonasJurczok** [comment]
> My reasoning would be that it is unlikely to release a version with one but not the other. Ultimately it is not important though D

I stand corrected. And it turns out to be the right decision to do this separately :D
