### ISSUE TITLE
Open edit dialog when clicking task name

### ISSUE THREAD

**Issue by hoylemd** [JonasJurczok/factorio-todo-list#46]
This was an idea I had while playing the other day - it'd be nice to be able to just click on the task's text to open the edit dialog.  It could mean eliminating the need for the `edit` button entirely, but that would need some styling to make it look clickable (if that's even possible), or made into a button.

**Comment by Tarrke** [comment]
To make it look like clickable? What do you have in mind?

**Comment by hoylemd** [comment]
Not sure, really.  I think there are some style settings that allow the font colour to change when you mouse-over a label.

I'm not sure if this is even possible, much less good.  Worth trying at least?

**Comment by Tarrke** [comment]
Really not sure this is feasible with lua. In js on a web page no problem
but here...

Le mar. 7 août 2018 à 20:57, Michael D. Hoyle <notifications@github.com> a
écrit :

**Comment by JonasJurczok** [comment]
As far as I know there is no way to do that. At least not with the standard
event handlers.

I also would prefer this on double click because otherwise scrolling the
to-do list with a trackpad or similar can become very frustrating :)

If you want feel free to experiment with this, though :))

Tarrke <notifications@github.com> schrieb am Di., 7. Aug. 2018, 21:52:

**Comment by hoylemd** [comment]
That's the plan! (to experiment with it)

**Comment by Tarrke** [comment]
Found a way to open the dialog on the right click, can be set to middle click too.

**Comment by Tarrke** [comment]
Added an option to change the button. It is a True/False option that switch between Middle/Right click. Seems operational to me.

**Comment by JonasJurczok** [comment]
Okay, nice. I'll take a look.

>
